const sessions=[
 {t:'Qui ? Où ? Que se passe-t-il ?',o:'Observer une image et construire un premier récit.',img:'assets/gare-mysterieuse.png',cap:'Qui est cette personne ? Que contient la valise ? Que va-t-il se passer ?',steps:[['0–10','Observer','Je vois / Je pense / J’imagine'],['10–25','Préparer','Personnes, actions, émotions'],['25–60','Raconter','Une histoire en binômes'],['60–90','Créer','Une minute avec 3 connecteurs']],words:['Je vois…','Je pense que…','Peut-être que…','Soudain…'],q:'Quelle phrase est une observation ?',c:['Je vois une femme avec une clé.','Je pense qu’elle cherche son frère.','Peut-être qu’elle est détective.'],a:0,p:'Décris ce que tu vois, sans inventer. Puis ajoute une hypothèse.'},
 {t:'Une BD sans paroles',o:'Raconter une suite d’images avec des connecteurs.',img:'assets/bd-sans-paroles.png',cap:'Regarde les trois images : imagine l’histoire entre chaque moment.',steps:[['0–15','Observer','Prédire la suite'],['15–30','Organiser','D’abord, ensuite, puis, soudain'],['30–65','Raconter','Sans lire de texte'],['65–90','Transformer','Inventer une autre fin']],words:['d’abord','ensuite','puis','soudain','finalement'],q:'Quel connecteur annonce une surprise ?',c:['D’abord','Soudain','Finalement'],a:1,p:'Raconte la BD à ton partenaire. Il doit ajouter la dernière phrase.'},
 {t:'Tout allait bien…',o:'Raconter un événement inattendu au passé.',img:'assets/bd-sans-paroles.png',cap:'Tout allait bien… jusqu’à ce qu’un problème arrive.',steps:[['0–10','Lancer','« Hier, ma journée avait bien commencé… »'],['10–25','Trouver','Perdre, casser, rater, tomber'],['25–60','Raconter','Lieu + problème + personne'],['60–90','Reprendre','Un autre apprenant continue']],words:['oublier','perdre','casser','rater','découvrir'],q:'Quel temps sert à présenter le contexte ?',c:['L’imparfait','Le passé composé','Le futur'],a:0,p:'Utilise l’imparfait pour le décor, puis le passé composé pour la surprise.'},
 {t:'Une rencontre improbable',o:'Improviser une rencontre entre deux personnages.',steps:[['0–10','Choisir','Deux personnalités'],['10–25','Installer','Gare, avion, ascenseur ou restaurant'],['25–45','Préparer','5 mots-clés'],['45–90','Jouer','Changer l’émotion puis raconter la suite']],words:['Il/elle a l’air de…','Qu’est-ce que vous faites ici ?','Je ne m’attendais pas à…'],q:'Choisis la phrase utile pour commencer.',c:['Qu’est-ce que vous faites ici ?','J’ai fini mes devoirs.','Il est huit heures.'],a:0,p:'Les deux personnages ont le même objet, mais ils ne le savent pas.'},
 {t:'Avant / pendant / après',o:'Construire une séquence et renforcer les temps du passé.',steps:[['0–10','Décrire','Avant : le décor'],['10–25','Ordonner','Pendant : l’événement'],['25–60','Enrichir','Après : la conséquence'],['60–90','Défier','5 connecteurs imposés']],words:['pendant que','quand','à ce moment-là','quelques minutes plus tard'],q:'Quelle expression montre deux actions simultanées ?',c:['Pendant que','Finalement','Après'],a:0,p:'Raconte un accident drôle avec « pendant que » et « quand ». '},
 {t:'Dans la tête du personnage',o:'Inventer un dialogue, des pensées et des émotions.',img:'assets/bd-sans-paroles.png',cap:'Choisis un personnage : que dit-il ? Que pense-t-il vraiment ?',steps:[['0–10','Observer','Que veut-il ?'],['10–25','Parler','Inventer les paroles'],['25–40','Penser','Paroles ≠ pensées'],['40–90','Jouer','Même dialogue, émotions différentes']],words:['Attends !','Ce n’est pas possible !','Je plaisante !','Au secours !'],q:'Quelle émotion transforme une même phrase ?',c:['La peur','Le lundi','Le français'],a:0,p:'Joue le même dialogue avec joie, peur, puis colère.'},
 {t:'Construisons une histoire',o:'Improviser collectivement avec les cartes.',steps:[['0–10','Échauffer','5 mots, une mini-histoire'],['10–25','Tirer','Personnage + lieu + objet + problème'],['25–60','Construire','Une information par personne'],['60–90','Résumer','60 secondes, puis 30 secondes']],words:['détective','gare','valise','lettre','secret','disparaître'],q:'De quoi as-tu besoin pour une histoire complète ?',c:['Un personnage, un lieu, un problème','Seulement un mot','Une règle'],a:0,p:'Tire les cartes. Chaque personne ajoute une phrase et un connecteur.'},
 {t:'Grand Storytelling Challenge',o:'Raconter une histoire originale pendant 2 à 3 minutes.',img:'assets/gare-mysterieuse.png',cap:'Choisis une image ou les cartes, puis raconte ton histoire finale.',steps:[['0–10','Improviser','5 mots'],['10–25','Choisir','Image, BD ou cartes'],['25–40','Préparer','Mots-clés uniquement'],['40–90','Présenter','2 à 3 minutes et questions']],words:['au début','ensuite','soudain','à ce moment-là','finalement'],q:'Pour le défi B1, que peux-tu ajouter ?',c:['Un dialogue et un rebondissement','Une liste de verbes','Rien'],a:0,p:'Ajoute une émotion forte, une raison et une fin inattendue.'}
];
const deck={Personnage:['un détective','une grand-mère','un touriste','une chanteuse','un voisin mystérieux'],Lieu:['une gare','un hôtel','un musée','un ascenseur','une forêt'],Objet:['une valise','une vieille clé','une lettre','un téléphone','une photo'],Problème:['quelqu’un disparaît','un secret est découvert','quelqu’un ment','une porte est bloquée','quelque chose est volé']};
const challenges=['Ajoute une émotion forte.','Un autre personnage arrive.','Raconte ce qui s’est passé avant.','L’objet devient important à la fin.','Change complètement la fin.'];
const thematicVocabulary=[['la gare','le quai','un train','une valise','une clé','mystérieux / mystérieuse','inquiet / inquiète','chercher','attendre','disparaître'],['une vignette','une scène','un personnage','une action','un début','une fin','tomber','aider','surprendre','raconter'],['une journée','un problème','un accident','un retard','oublier','perdre','casser','rater','être en panne','tout à coup'],['se rencontrer','un inconnu','un voisin','un voyageur','un rendez-vous','reconnaître','inviter','discuter','timide','surpris / surprise'],['avant','pendant','après','la météo','tout à coup','pendant que','quand','à ce moment-là','ensuite','quelques minutes plus tard'],['une pensée','un dialogue','un secret','une intention','avoir peur','être soulagé','être en colère','être gêné','croire','espérer'],['un héros','un lieu','un objet','un problème','un indice','un secret','résoudre','découvrir','mentir','sauver'],['le début','le rebondissement','la fin','une émotion','une raison','un détail','soudain','finalement','heureusement','malheureusement']];
const germanVocabulary=[['der Bahnhof','der Bahnsteig','ein Zug','ein Koffer','ein Schlüssel','geheimnisvoll','besorgt','suchen','warten','verschwinden'],['ein Bildfeld','eine Szene','eine Figur','eine Handlung','ein Anfang','ein Ende','fallen','helfen','überraschen','erzählen'],['ein Tag','ein Problem','ein Unfall','eine Verspätung','vergessen','verlieren','kaputtmachen','verpassen','eine Panne haben','plötzlich'],['sich begegnen','ein Unbekannter','ein Nachbar','ein Reisender','ein Treffen','wiedererkennen','einladen','sich unterhalten','schüchtern','überrascht'],['vorher','während','nachher','das Wetter','plötzlich','während','als / wenn','in diesem Moment','danach','ein paar Minuten später'],['ein Gedanke','ein Dialog','ein Geheimnis','eine Absicht','Angst haben','erleichtert sein','wütend sein','verlegen sein','glauben','hoffen'],['ein Held','ein Ort','ein Gegenstand','ein Problem','ein Hinweis','ein Geheimnis','lösen','entdecken','lügen','retten'],['der Anfang','die Wendung','das Ende','ein Gefühl','ein Grund','ein Detail','plötzlich','schließlich','zum Glück','leider']];
const sessionGerman=[['Ich sehe…','Ich denke, dass…','Vielleicht…','Plötzlich…'],['zuerst','danach','dann','plötzlich','schließlich'],['vergessen','verlieren','kaputtmachen','verpassen','entdecken'],['Er/sie sieht … aus','Was machen Sie hier?','Ich habe nicht erwartet, …'],['während','als / wenn','in diesem Moment','ein paar Minuten später'],['Warte!','Das ist nicht möglich!','Ich mache nur Spaß!','Hilfe!'],['Detektiv','Bahnhof','Koffer','Brief','Geheimnis','verschwinden'],['am Anfang','danach','plötzlich','in diesem Moment','schließlich']];
let current=0,done=new Set(JSON.parse(localStorage.getItem('story-passport')||'[]'));const $=q=>document.querySelector(q),pick=a=>a[Math.floor(Math.random()*a.length)],nav=$('#nav'),workspace=$('#workspace');
function update(){ $('#count').textContent=`${done.size} / 8`;$('#bar').style.width=`${done.size/8*100}%`;localStorage.setItem('story-passport',JSON.stringify([...done])) }
function makeCards(){return Object.entries(deck).map(([name,values])=>`<div class="story"><span>${name}</span><strong>${pick(values)}</strong></div>`).join('')}
function render(){const s=sessions[current];$('#label').textContent=`Séance ${current+1} sur 8`;document.querySelectorAll('.session').forEach((b,i)=>b.classList.toggle('active',i===current));workspace.innerHTML=`<article class="hero"><div class="copy"><div class="meta"><span>SÉANCE ${current+1} · 1 H 30</span><span class="badge">${current<3?'GUIDÉE':'CRÉATIVE'}</span></div><h2>${s.t}</h2><p>${s.o}</p></div>${s.img?`<figure><img src="${s.img}" alt="Support visuel de la séance ${current+1}"><figcaption>${s.cap}</figcaption></figure>`:''}</article><div class="grid"><article class="card"><h3>Déroulement de la séance</h3><p>Suivez les étapes ou adaptez-les à votre groupe.</p><div class="phases">${s.steps.map(x=>`<div class="phase"><time>${x[0]}</time><div><strong>${x[1]}</strong><span>${x[2]}</span></div></div>`).join('')}</div><div class="prompt"><strong>Consigne à dire à la classe</strong><br>${s.p}</div>${s.words.map(x=>`<span class="pill">${x}</span>`).join('')}</article><aside class="card"><h3>Atelier interactif</h3><p>${s.q}</p><div class="choice-grid">${s.c.map((x,i)=>`<button class="choice" data-choice="${i}">${x}</button>`).join('')}</div><div class="feedback" id="feedback"></div><hr><h3>Cartes à histoires</h3><p>Tirez une combinaison pour lancer une improvisation.</p><div class="stories" id="stories">${makeCards()}</div><div class="buttons"><button class="secondary" id="draw">Nouvelles cartes</button><button class="secondary" id="challenge">Défi surprise</button></div><div class="challenge" id="challenge-text">Conseil : commence par « Au début… ».</div><div id="timer-slot"></div></aside></div><button class="complete ${done.has(current)?'done':''}" id="complete">${done.has(current)?'✓ Séance validée dans mon passeport':'Valider cette séance dans mon passeport'}</button>`;$('#timer-slot').append($('#timer').content.cloneNode(true));wire(s)}
function wire(s){document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const ok=Number(b.dataset.choice)===s.a;document.querySelectorAll('[data-choice]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');$('#feedback').textContent=ok?'✓ Très bien ! Utilisez cette idée dans votre récit.':'Réessaie : regarde les mots-clés de la séance.'});$('#draw').onclick=()=>$('#stories').innerHTML=makeCards();$('#challenge').onclick=()=>$('#challenge-text').textContent='⚡ '+pick(challenges);$('#complete').onclick=()=>{done.add(current);update();render()};let seconds=60,running=false,interval,display=$('.timer b'),button=$('.timer button');button.onclick=()=>{if(running){clearInterval(interval);running=false;button.textContent='Continuer';return}running=true;button.textContent='Pause';interval=setInterval(()=>{if(seconds===0){clearInterval(interval);running=false;button.textContent='Encore 1 min';seconds=60;return}seconds--;display.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000)}}
sessions.forEach((s,i)=>{const b=document.createElement('button');b.className='session';b.innerHTML=`<span class="num">${i+1}</span><span class="name">${s.t}</span>`;b.onclick=()=>{current=i;render();scrollTo({top:0,behavior:'smooth'})};nav.append(b)});$('#reset').onclick=()=>{done.clear();update();render()};update();render();

const renderBase=render;
render=function(){
  renderBase();
  document.querySelectorAll('.grid .card:first-child .pill').forEach((pill,index)=>{
    pill.innerHTML=`${pill.textContent}<br><strong style="color:#293451;font-size:.78rem">🇩🇪 ${sessionGerman[current][index]}</strong>`;
  });
  const vocab=document.createElement('div');
  vocab.className='prompt';
  vocab.innerHTML=`<strong>Vocabulaire du thème · français — allemand</strong><br><span style="color:#687086;font-size:.84rem">Pour comprendre et enrichir votre histoire :</span><div style="margin-top:8px">${thematicVocabulary[current].map((word,index)=>`<span class="pill">${word}<br><strong style="color:#293451;font-size:.78rem">🇩🇪 ${germanVocabulary[current][index]}</strong></span>`).join('')}</div>`;
  document.querySelector('.grid .card').append(vocab);
  const board=document.createElement('section');
  board.className='card';board.style.marginTop='18px';
  board.innerHTML=`<h3>Tableau blanc — séance ${current+1}</h3><p>Écrivez les idées, phrases ou corrections à garder pour cette séance.</p><textarea id="whiteboard" aria-label="Tableau blanc" placeholder="Écrivez ici…" style="width:100%;min-height:180px;resize:vertical;border:1px solid #cfc9bf;border-radius:10px;padding:12px;font:inherit;background:#fff"></textarea><div class="buttons"><button class="secondary" id="clear-board">Effacer le tableau</button></div>`;
  workspace.insertBefore(board,$('#complete'));
  const whiteboard=$('#whiteboard'),key=`story-whiteboard-${current}`;
  whiteboard.value=localStorage.getItem(key)||'';
  whiteboard.addEventListener('input',()=>localStorage.setItem(key,whiteboard.value));
  $('#clear-board').onclick=()=>{whiteboard.value='';localStorage.removeItem(key)};
};
render();
